### ISSUE TITLE
关于 fork 的 aliyun-m3u8-downloader 项目处理

### ISSUE THREAD

**Issue by lbbniu** [52beijixing/52beijixing#1]
您好，感谢您fork aliyun-m3u8-downloader 项目，对 aliyun-m3u8-downloader 项目的支持，此项目存在法律风险，请配合删除或者修改项目为私有，感谢您的支持，处理后请回复邮件确认处理结果

**Comment by 52beijixing** [comment]
> 您好，感谢您fork aliyun-m3u8-downloader 项目，对 aliyun-m3u8-downloader 项目的支持，此项目存在法律风险，请配合删除或者修改项目为私有，感谢您的支持，处理后请回复邮件确认处理结果

好的，马上私有。十分抱歉今天才看到

**Comment by 52beijixing** [comment]
> 您好，感谢您fork aliyun-m3u8-downloader 项目，对 aliyun-m3u8-downloader 项目的支持，此项目存在法律风险，请配合删除或者修改项目为私有，感谢您的支持，处理后请回复邮件确认处理结果

十分抱歉才看到，我会马上进行删除的。
